on: [push]

name: test

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Apeworx Vyper project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.vvm/vyper-*
          key: compiler-cache

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install Vyper
        run: pip install vyper

      - name: Install Apeworx
        run: pip install eth-ape

      - name: Install Ape Plugins
        run: ape plugins install vyper

      - name: Run Tests
        run: ape test